name: Test Email Report

on:
  workflow_dispatch:  # Триггер для ручного запуска

jobs:
  test-email:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Использование Node.js 20

    - name: Get closed issues from last week
      id: get_issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LAST_WEEK=$(date --utc --date="7 days ago" '+%Y-%m-%dT%H:%M:%SZ')
        curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=closed&since=$LAST_WEEK" \
          | jq '.[] | "- [\(.title)](\(.html_url))"' > report.txt

    - name: Read report content
      id: read_report
      run: |
        if [ -s report.txt ]; then
          REPORT_CONTENT=$(cat report.txt)
          echo "report_content=$REPORT_CONTENT" >> $GITHUB_ENV
        else
          echo "report_content=No issues closed this week." >> $GITHUB_ENV

    - name: Send email with report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}  # Gmail логин
        password: ${{ secrets.EMAIL_PASSWORD }}  # App Password для Gmail
        subject: Weekly Closed Issues Report
        body: ${{ env.report_content }}  # Используем содержимое файла
        to: timarnd06@gmail.com
        from: timarnd06@gmail.com
