name: Test Email Report

on:
  workflow_dispatch:  # Триггер для ручного запуска

jobs:
  test-email:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Использование Node.js 20

    - name: Get closed issues and comments
      run: |
        echo "Fetching closed issues..."
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?state=closed")
        echo "Response from GitHub API: $response"
        if [ -z "$response" ]; then
          echo "No issues found." > report.txt
        else
          # Обрабатываем каждую задачу
          echo "$response" | jq -r '.[] | select(.html_url and .title and .body) | 
            "- [\(.title)](\(.html_url))\n\n\(.body)\n\nComments:\n\(.comments_url | @sh) | jq -r \\".[] | .body\\""' > report.txt
        fi

    - name: Check if issues were found
      run: |
        if [ -s report.txt ]; then
          echo "Found closed issues"
          cat report.txt
        else
          echo "No closed issues found." > report.txt
        fi

    - name: Upload report.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: weekly-report
        path: report.txt

    - name: Download report artifact
      uses: actions/download-artifact@v3
      with:
        name: weekly-report

    - name: Read report content
      id: read-report
      run: |
        report_content=$(cat report.txt)
        echo "report_content<<EOF" >> $GITHUB_ENV
        echo "$report_content" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Send email with report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}  # Добавьте это в секцию Secrets
        password: ${{ secrets.EMAIL_PASSWORD }}  # Добавьте это в секцию Secrets
        subject: Weekly Closed Issues Report
        body: ${{ env.report_content }}  # Использование переменной из шага "Read report content"
        to: timarnd06@gmail.com
        from: timarnd06@gmail.com
