name: Test Email Report

on:
  workflow_dispatch:  # Триггер для ручного запуска

jobs:
  test-email:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Использование Node.js 20

    - name: Generate example report
      run: |
        echo "Weekly Closed Issues Report:" > report.txt
        echo "- [Example Issue](https://github.com/example/repo/issues/1)" >> report.txt
        echo "- [Another Issue](https://github.com/example/repo/issues/2)" >> report.txt

    - name: Send email with report
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}  # Добавьте это в секцию Secrets
        password: ${{ secrets.EMAIL_PASSWORD }}  # Добавьте это в секцию Secrets
        subject: Weekly Closed Issues Report
        body: |
          $(cat report.txt)
        to: timarnd06@gmail.com
        from: timarnd06@gmail.com
